# Generated by Django 2.2.13 on 2020-08-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCapture', '0008_staff_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='finger_print',
            field=models.BinaryField(default=b''),
        ),
    ]
