# Generated by Django 2.2.13 on 2020-08-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCapture', '0009_staff_finger_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='finger_print',
            field=models.BinaryField(default=b'', null=True),
        ),
    ]
